<?php
    $errors = $_GET['errors'] ?? [];
?>
<div class="row" style="justify-content: center">
    <div class="col-lg-6 col-md-8 col-sm-10">
        <h1 class="h3 mb-3 text-center">Please sign in</h1>
        <form class="form-signin p-4 rounded-3 shadow-sm" method="post" style="background: #fff">
            <div class="form-group">
                <label for="inputEmail">Email address</label>
                <input type="text" id="inputEmail" class="form-control" name="username" placeholder="Email address" required autofocus>
            </div>
            <div class="form-group">
                <label for="inputPassword">Password</label>
                <input type="password" id="inputPassword" class="form-control" name="password" placeholder="Password" required>
            </div>

            <?php if (!empty($errors)): ?>
                <div class="alert alert-danger">
                    <?php foreach ($errors as $error): ?>
                        <?= $error; ?><br>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button><br>
            <small>Don't have an account? Register <a href="index.php?action=register">here</a> for free.</small>
        </form>
    </div>
</div>