<?php
/**
 * @var array $current_user
 * @var array $stats
 */
$error = $_GET['error'] ?? null;
?>
<h3>Welcome <?= $current_user['username'] ?></h3>
<?php if ($error != null): ?>
    <div class="alert alert-warning">
        <?= $error ?>
    </div>
<?php endif; ?>

<div class="row mb-3">
    <div class="col-lg-3 col-6">
        <div class="small-box bg-info p-1">
            <div class="inner">
                <h3><?= $stats['users'] ?></h3>
                <p>Total Users</p>
            </div>
            <div class="icon">
                <i class="ion ion-bag"></i>
            </div>
            <a href="index.php?page=user&action=users" class="small-box-footer">View all users <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <div class="col-lg-3 col-6">
        <div class="small-box bg-success p-1">
            <div class="inner">
                <h3>53<sup style="font-size: 20px">%</sup></h3>
                <p>Bounce Rate</p>
            </div>
            <div class="icon">
                <i class="ion ion-stats-bars"></i>
            </div>
            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <div class="col-lg-3 col-6">
        <div class="small-box bg-warning p-1">
            <div class="inner">
                <h3><?= $stats['posts'] ?></h3>
                <p>Blog posts</p>
            </div>
            <div class="icon">
                <i class="ion ion-person-add"></i>
            </div>
            <a href="index.php?page=post&action=posts" class="small-box-footer">View Posts <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <div class="col-lg-3 col-6">
        <div class="small-box bg-danger p-1">
            <div class="inner">
                <h3><?= $stats['visits'] ?></h3>
                <p>Total Visits</p>
            </div>
            <div class="icon">
                <i class="ion ion-pie-graph"></i>
            </div>
            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
</div>