<?php
/**
 * @var array $to_delete
 */
?>
<h2>Delete Confirmation</h2>
<form method="post">
    <p>Are you sure you want to delete this user?</p>
    <p>Username: <strong><?= $to_delete['username'] ?></strong></p>
    <p>Email: <strong><?= $to_delete['email'] ?></strong></p>
    <input type="hidden" name="confirm" value="1">
    <input type="hidden" name="id" value="<?= $to_delete['id'] ?>">
    <button type="submit" class="btn btn-danger">Yes, Delete it</button>
    <a class="btn btn-secondary" href="index.php?page=user&action=users">Cancel</a>
</form>