<?php
/**
 * @var array $to_edit
 * @var array $user
 */
$errors = $_GET['errors'] ?? [];
?>
<div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
        <h1 class="h3 mb-3 font-weight-normal">Edit User Data</h1>
        <form class="form-signin" method="post">
            <div class="form-group mb-3">
                <label for="username">Username</label>
                <input type="text" id="username" class="form-control" name="username" placeholder="Username" value="<?= $to_edit['username'] ?>">
            </div>
            <div class="form-group mb-3">
                <label for="inputEmail">Email address</label>
                <input type="text" id="inputEmail" class="form-control" name="email" placeholder="Email address" value="<?= $to_edit['email'] ?>">
            </div>
            <div class="form-group mb-3">
                <label for="password">Password</label>
                <input type="password" id="password" class="form-control" name="password" placeholder="Password">
                <small class="form-text text-muted">Leave empty if you don't want to change it.</small>
            </div>
            <div class="form-group mb-3">
                <label for="passwordRepeat">Password Repeat</label>
                <input type="password" autocomplete="off" id="passwordRepeat" class="form-control" name="password_repeat" placeholder="Password Repeat">
                <small class="form-text text-muted">Passwords should match.</small>
            </div>
            <?php if (!empty($errors)): ?>
                <div class="alert alert-danger">
                    <?php foreach ($errors as $error): ?>
                        <?= $error; ?><br>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
            <input type="hidden" name="id" value="<?= $to_edit['id'] ?>">
            <button class="btn btn-primary" type="submit"><i class="fa fa-save"></i> Save</button>
            <a href="index.php?page=user&action=users" class="btn btn-secondary"><i class="fa fa-backward"></i> Go Back</a>
        </form>
    </div>
</div>
