<?php
/**
 * @var array $users
 * @var array $current_user
 */
$error = $_GET['error'] ?? null;
?>
<section style="margin-left: 2%">
    <div class="row">
        <div class="col-md-12">
            <h4 class="text-center mb-4">All users</h4>
            <?php if ($error != null): ?>
            <div class="alert alert-warning">
                <?= $error ?>
            </div>
            <?php endif; ?>
            <div class="table-wrap">
                <table class="table table-striped table-hover">
                    <thead class="thead-primary">
                    <tr>
                        <th>Id</th>
                        <th>Username</th>
                        <th>Email</th>
                        <th>Role</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($users as $user): ?>
                        <tr>
                            <td><?= $user['id'] ?></td>
                            <td><?= $user['username'] ?></td>
                            <td><?= $user['email'] ?></td>
                            <td><?= $user['role'] ?></td>
                            <td>
                                <?php if ($user['id'] != $current_user['id']): ?>
                                <div style="display:flex;">
                                    <a class="btn btn-warning mr-2" href="index.php?page=user&action=edit&id=<?= $user['id'] ?>"><i class="fa fa-edit"></i> Edit</a>
                                    <form method="post" action="index.php?page=user&action=delete" class="mr-2">
                                        <input type="hidden" name="id" value="<?= $user['id'] ?>">
                                        <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i> Delete</button>
                                    </form>
                                </div>
                                <?php else: ?>
                                <em class="text-center">This is you</em>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>