<?php
/**
 * @var array $categories
 * @var \App\Model\Auth $auth
 */
?>
<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="index.php">Sadik MVC</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="index.php">All Posts</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="categoryDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Categories</a>
                    <ul class="dropdown-menu" aria-labelledby="categoryDropdown">
                        <?php foreach ($categories as $cat): ?>
                        <li><a class="dropdown-item" href="index.php?page=blog&action=category&id=<?= $cat['id'] ?>"><?= $cat['category'] ?></a></li>
                        <?php endforeach; ?>
                    </ul>
                </li>
                <?php if ($auth->isLoggedIn()): ?>
                <li class="nav-item"><a class="nav-link" href="<?= WEB_URL ?>index.php?page=dashboard">Dashboard</a></li>
                <?php endif; ?>
            </ul>
            <?php if (!$auth->isLoggedIn()): ?>
            <a href="index.php?action=login" class="btn btn-outline-primary me-2">Login</a>
            <a href="index.php?action=register" class="btn btn-outline-primary">Register</a>
            <?php endif; ?>
        </div>
    </div>
</nav>
