<?php
/**
 * @var string $template
 */
$auth = new \App\Model\Auth();
$current_user = $auth->getCurrentUser();
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>Welcome</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="<?= WEB_URL ?>css/admin/adminlte.min.css" rel="stylesheet">
    <link href="<?= WEB_URL ?>css/admin/admin.css" rel="stylesheet">
</head>
<body>
<div class="wrapper d-flex align-items-stretch">
    <?php include TEMPLATES . 'layout/admin/sidebar.phtml'; ?>
    <div id="content" class="p-3 p-md-3 ml-4 mt-3">
        <?php include TEMPLATES . $template . '.phtml'; ?>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" ></script>
<script src="https://getbootstrap.com/docs/4.5/dist/js/bootstrap.bundle.min.js"></script>
<script>
    $('#sidebarCollapse').on('click', function () {
        $('#sidebar').toggleClass('active');
    });
</script>
</body>
</html>