<?php
/**
 * @var array $task
 */
?>
<h2>Delete Confirmation</h2>
<form method="post">
    <p>Are you sure you want to delete this user?</p>
    <p><strong>Title:</strong> <?= $task['title'] ?></p>
    <p><strong>Note:</strong> <?= strlen($task['note'] ?? '') > 0 ? nl2br($task['note']) : '<em>No Note</em>' ?></p>
    <p><strong>Date:</strong> <?= $task['date'] ?? '<em>No Date</em>' ?></p>
    <input type="hidden" name="confirm" value="1">
    <input type="hidden" name="id" value="<?= $task['id'] ?>">
    <button type="submit" class="btn btn-danger">Yes, Delete it</button>
    <a class="btn btn-secondary" href="index.php?page=task&action=index">Cancel</a>
</form>