<?php
/**
 * @var array $tasks
 * @var array $current_user
 */
$errors = $_GET['errors'] ?? null;
$success = $_GET['success'] ?? null;
?>
<section style="margin-left: 2%">
    <div class="row">
        <div class="col-md-12">
            <h4 class="mb-4">My Tasks</h4>
            <?php if (!empty($errors)): ?>
                <div class="alert alert-danger">
                    <?php foreach ($errors as $error): ?>
                        <?= $error; ?><br>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
            <?php if ($success != null): ?>
                <div class="alert alert-success">
                    <?= $success ?>
                </div>
            <?php endif; ?>
            <div class="table-wrap">
                <table class="table table-striped table-hover">
                    <thead class="thead-primary">
                    <tr>
                        <th>Id</th>
                        <th>Title</th>
                        <th>Note</th>
                        <th>Time</th>

                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($tasks as $task): ?>
                        <tr>
                            <td><?= $task['id'] ?></td>
                            <td><?= $task['title'] ?></td>
                            <td><?= $task['note'] ?></td>
                            <td><?= $task['time'] ?></td>
                            <td>
                                <?php if ($task['user_id'] == $current_user['id']): ?>
                                <div style="display:flex;">
                                    <a class="btn btn-warning mr-2" href="index.php?page=task&action=edit&id=<?= $task['id'] ?>"><i class="fa fa-edit"></i> Edit</a>
                                    <form method="post" action="index.php?page=task&action=delete" class="mr-2">
                                        <input type="hidden" name="id" value="<?= $task['id'] ?>">
                                        <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i> Delete</button>
                                    </form>
                                </div>
                                <?php else: ?>
                                <em class="text-center">No permission</em>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    <?php if (count($tasks) == 0): ?>
                    <tr>
                        <td colspan="3" class="text-center">
                            <em>You have no tasks. Create one <a href="index.php?page=task&action=new">here</a>.</em>
                        </td>
                    </tr>
                    <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>